### ISSUE TITLE
eGPU detected but doesn't start

### ISSUE THREAD

**Issue by miguelmsa1** [mayankk2308/purge-wrangler#57] opened 2020-03-31 18:43 UTC
**System Configuration**
Mac: Macbook Pro Late 2011 13" (MBP 8,1)
macOS Version: 10.13.6 (17G12034)
System GPUs: Intel HD 3000 512MB
eGPU: AORUS Gaming Box + NVIDIA GeForce GTX 1060 6GB
Script Version: 6.2.3
Script Logs: [pwlog-2020-03-31-19-22-02.zip](https://github.com/mayankk2308/purge-wrangler/files/4410923/pwlog-2020-03-31-19-22-02.zip)

**Issue Description**
I'm having troubles to make my build work. My MBP has a TB1 port, for this reason, yesterday I bought a TB (1/2) cable & a TB3 to TB2/TB1 adapter.
After installing the script and web drivers, I can see both graphic cards listed in "System Information" and "About this Mac", but when I try to monitor the performance with Activity Monitor, it only shows 1 GPU with the title of "NVIDIA GeForce GTX 1060 6GB" even knowing that this Application is using the integrated graphic card.

The fans of eGPU aren't working, and the Applications don't show a better performance even when using a Monitor connected through HDMI directly to the eGPU case.

I tried to use the script "set-egpu" too with some programs without success. 

Can somebody help me? I'll be eternally grateful!

Thanks in advance.

![Captura de pantalla 2020-03-31 a las 21 02 57](https://user-images.githubusercontent.com/2528887/78065239-439d7200-7393-11ea-89b3-282dfb9a5e73.png)
![Captura de pantalla 2020-03-31 a las 21 02 25](https://user-images.githubusercontent.com/2528887/78065255-4a2be980-7393-11ea-8078-1bda675fda69.png)
![Captura de pantalla 2020-03-31 a las 21 03 10](https://user-images.githubusercontent.com/2528887/78065266-5021ca80-7393-11ea-9860-aa6b772a17e8.png)
![Captura de pantalla 2020-03-31 a las 21 04 16](https://user-images.githubusercontent.com/2528887/78065273-53b55180-7393-11ea-9133-bc084aa5960e.png)

**Comment by mayankk2308** [comment] 2020-04-01 00:48
Set eGPU as the primary display. I have never seen the iGPU vanish from Activity Monitor and am not sure what the cause is. Unfortunately this issue is not directly related to the script so am closing. Consider reaching out on egpu.io for more assistance.

**Closed by mayankk2308** 2020-04-01 00:48 UTC
