### ISSUE TITLE
AMD GPU detected as “display” on 2013 Mac Pro

### ISSUE THREAD

**Issue by kiddo71** [mayankk2308/purge-wrangler#81] opened 2020-06-11 07:40 UTC
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacPro Late2013
- **macOS Version**: 10.15.5
- **System GPUs**: Dual FirePro D300
- **eGPU**: Sonnet Breakaway 650 + AMD Vega 64
- **Script Version**: 6.2.5
[pwlog-2020-06-11-09-23-47.zip](https://github.com/mayankk2308/purge-wrangler/files/4763278/pwlog-2020-06-11-09-23-47.zip)

- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
After a system upgrade to 10.15.5 the Video Card is not recognised by the system.
This is a System Report data:

Tipo:	GPU esterna
  Bus:	PCIe
  Larghezza canale PCIe:	x16
  Fornitore:	AMD (0x1002)
  ID dispositivo:	0x687f
  ID revisione:	0x00c1
  Cambio automatico scheda grafica:	Supportata
  Versione gMux:	4.0.11 [3.2.8]

The eGPU icon is missing
The installation script detects the right Video Card 
The eGPU box is reported correctly in the system report

### Expected Behavior
Just working as before ; it worked fine till 10.15.4 system. Failed to load after installing latest update.

**Comment by mayankk2308** [comment] 2020-06-11 07:51
I will have to investigate this once I have time.

**Comment by mayankk2308** [comment] 2020-06-14 04:48
@kiddo71 I received confirmation that the script works fine on the 2013 Mac Pro + 10.15.5 (and even 10.15.6 B2). Try the following steps:
1. Run **purge-wrangler** uninstall option.
2. Reboot system.
3. Rebuild kextcache again:
    ```
    sudo kextcache -i /
    ```
4. Setup eGPU again using the script.
5. Check if eGPU is working. If not, repeat step 3, reboot and re-check.

You mentioned that eGPU was working fine before - has anything else changed besides updating macOS (you re-assembled the eGPU, etc.)?

**Comment by kiddo71** [comment] 2020-06-14 09:08
Great to hear.

The mac configuration is unchanged.
The only changed thing is the 10.15.5 update.

I have done the same process as usual.
The mac was non changed in any part , neither hardware or software.

I usually full remove cache folders before system update.

**Comment by kiddo71** [comment] 2020-06-15 08:52
Hello.
I did all the procedure this morning.

1) ok
2) done immediately after uninstall
3) Done:

This is the echo:
IOKitWaitQuiet() timed out.
KernelCache ID: 65260F93774408FADD4AA4CE5F76F579

4) done, the Video Card is recognised correctly , reboot
5) not working; try to disconnect and reconnect the cable. The eGPU appears just a few seconds (report NO EGPU CONNECTED)

6) again step 3

This is the echo
IOKitWaitQuiet() timed out.
Kext with invalid signature (-67061) allowed: <OSKext 0x7fe9d9e53730 [0x7fff8b363b60]> { URL = "file:///System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGPUWrangler.kext/", ID = "com.apple.AppleGPUWrangler" }
KernelCache ID: 65260F93774408FADD4AA4CE5F76F579
Kext with invalid signature (-67061) allowed: <OSKext 0x7fc6e3705c50 [0x7fff8b363b60]> { URL = "file:///System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGPUWrangler.kext/", ID = "com.apple.AppleGPUWrangler" }

7)not working; try to disconnect and reconnect the cable. No eGPU icon.

**Comment by mayankk2308** [comment] 2020-06-15 09:07
Your kernel cache is not being rebuilt properly. The next step would be to try and rebuild the kernel cache for your boot volume via recovery (look up instructions) mode. If that also does not work, your only alternatives are:
* Revert to 10.15.4 via backup.
* Upgrade to 10.15.6 beta to see if it fixes the issue.
* Clean install macOS and try. You can try this step by creating an extra APFS volume and checking before erasing your actual install. 

As such, the problem is not with the script, but something with macOS, hence closing the issue.

**Closed by mayankk2308** 2020-06-15 09:07 UTC

**Comment by kiddo71** [comment] 2020-06-17 08:53
Hello.

I did a clean install on an external disk with fresh full 10.15.5 install. (Just one user , no iCloud, just egpu)

I got the same issue.

Here is the log, if can help.

ciao

**Comment by mayankk2308** [comment] 2020-06-28 22:02
I don’t see the log for your clean install attempt.
