### ISSUE TITLE
Your system volume is read-only

### ISSUE THREAD

**Issue by need-better-name** [mayankk2308/purge-wrangler#117] opened 2020-11-16 16:18 UTC
Hello, I am getting the error "Your system volume is read-only. PurgeWrangler cannot proceed." when running the script. I've selected startup disk as indicated in the FAQ's.

I have a 2014 Mac mini with a 2.6 GHz Dual-Core Intel Core i5, 16 Gigs of RAM. My eGPU enclosure is a Sonnet eGFX Breakaway Box, Thunderbolt 3-to eGPU PCIe Card Expansion System (GPU-350W-TB3Z) and a Sapphire 11266-14-20G Radeon Nitro+ Rx 570 4GB GDDR5 Dual HDMI/ DVI-D/ Dual DP with Backplate (UEFI) PCI-E Graphics Card

**Comment by mayankk2308** [comment] 2020-11-16 19:45
What’s the output for this command: `bless —getBoot` when booted into Big Sur?

**Comment by need-better-name** [comment] 2020-11-16 19:48
/dev/disk2s5

**Comment by mayankk2308** [comment] 2020-11-16 19:52
Ok so that looks right to me. And you still get the error? Hmm. Try resetting NVRAM and then re-disabling all the SIP stuff and redoing the FAQ suggestion. Let me know how that goes.

**Comment by need-better-name** [comment] 2020-11-16 20:05
I just did all that, rest NVRAM, retyped the disable commands, and reselected my boot disk. Rebooting in between each step. Still the same error.

**Comment by Peterfvs** [comment] 2020-11-16 20:29
Same problem, iMac late 2014. If I do remember correctly I did get to the menu the first time I tried, but missed the "csrutil authenticated-root disable" so it failed. I then did the "csrutil authenticated-root disable" and now I get the "Your system volume is read-only. PurgeWrangler cannot proceed.
Please restart your Mac and try again." message.

**Comment by mayankk2308** [comment] 2020-11-16 20:43
@Peterfvs did you try recommendation in FAQ? https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#system-is-read-onlyefi-boot-device-error-and-purgewrangler-unable-to-proceed-on-macos-11

@need-better-name I cannot reproduce the issue on my system at this time. After disabling SIP as necessary and ensuring my system shows the `bless --getBoot` output correctly, the script just runs fine. Could you share output of `diskutil list` so I can get a look at what the layout of your system is?

**Comment by Peterfvs** [comment] 2020-11-16 20:52
Yes, while I tried this again on a new user (after PRAM zap), I first got the message "Can't access "efi-boot-device" NVRAM variable" but after a I selected the Harddrive I get the " Your system volume is read-only. PurgeWrangler cannot proceed.
Please restart your Mac and try again."  again.

**Comment by need-better-name** [comment] 2020-11-16 21:10
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk3⁩         121.1 GB   disk0s2

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk1
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk1s1
   2:                 Apple_APFS ⁨Container disk2⁩         1000.0 GB  disk1s2

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1000.0 GB  disk2
                                 Physical Store disk1s2
   1:                APFS Volume ⁨Macintosh HD 2⁩          742.6 GB   disk2s1

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +121.1 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Macintosh HD - Data⁩     63.3 GB    disk3s1
   2:                APFS Volume ⁨Preboot⁩                 284.8 MB   disk3s2
   3:                APFS Volume ⁨Recovery⁩                655.5 MB   disk3s3
   4:                APFS Volume ⁨VM⁩                      2.1 GB     disk3s4
   5:                APFS Volume ⁨Macintosh HD⁩            14.9 GB    disk3s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 14.9 GB    disk3s5s1

**Comment by need-better-name** [comment] 2020-11-16 21:18
@Peterfvs to fix the “Can't access "efi-boot-device" NVRAM variable”, you just need to select your boot volume in the system preferences.

**Comment by Peterfvs** [comment] 2020-11-16 21:27
And when I do that, then I'm back at "Your system volume is read-only".

**Comment by Peterfvs** [comment] 2020-11-16 21:39
#:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk2⁩         121.1 GB   disk0s2

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *3.0 TB     disk1
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk1s1
   2:                 Apple_APFS ⁨Container disk2⁩         3.0 TB     disk1s2

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +3.1 TB     disk2
                                 Physical Stores disk0s2, disk1s2
   1:                APFS Volume ⁨Macintosh HD – data⁩     511.7 GB   disk2s1
   2:                APFS Volume ⁨Preboot⁩                 286.7 MB   disk2s2
   3:                APFS Volume ⁨Recovery⁩                655.5 MB   disk2s3
   4:                APFS Volume ⁨VM⁩                      2.1 GB     disk2s4
   5:                APFS Volume ⁨Macintosh HD⁩            14.9 GB    disk2s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 14.9 GB    disk2s5s1

**Comment by Peterfvs** [comment] 2020-11-17 11:17
Made a new clean macOS Big Sur install on an external disk, and applied the patch with no problems.

**Comment by mayankk2308** [comment] 2020-11-18 13:04
@need-better-name you initially said that `bless --getBoot` gives you `/dev/disk2s5`, but from your list of disks, I am guessing the boot disk is "Macintosh HD" - which should be `/dev/disk3s5`. There is no `/dev/disk2s5` on your system as far as I see.

**Comment by bitnautist** [comment] 2020-11-18 14:17
On my system, bless --getBoot points to disk1s5 which is my Macintosh HD. If I do a diskutil info disk1s5, I get: 

"Device Identifier:         disk1s5
   Device Node:               /dev/disk1s5
   Whole:                     No
   Part of Whole:             disk1

   Volume Name:               Macintosh HD
   Mounted:                   No

info truncated  

   Media OS Use Only:         No
   Media Read-Only:           No
   Volume Read-Only:          Not applicable (not mounted)

info truncated

   Encrypted:                 No
   FileVault:                 No
   Sealed:                    Broken
   Locked:                    No"

Curiously it shows it's not mounted and that the Seal is broken.

Now if I do a diskutil mount disk1s5 to mount it and then do diskutil info disk1s5 again, I get basically everything the same as before except for:

"   Volume Name:               Macintosh HD
   Mounted:                   Yes
   Mount Point:               /Volumes/Macintosh HD 2"

Is that mount point "Macintosh HD 2" confusing the script if it's expecting only "Macintosh HD"?

Running the script at this point results in the same System is read-only error and disk1s5 goes back to being not mounted.

**Comment by mayankk2308** [comment] 2020-11-18 14:20
@bitnautist yes its mostly due to the appended number at the end. The script expects it to append **1** instead of **2**. I am planning a fix soon. Stay tuned.

**Comment by bitnautist** [comment] 2020-11-18 14:22
Interesting but why does it work on your system? There's some difference between our systems that causes mine to increment to a 2 instead of 1.

**Comment by mayankk2308** [comment] 2020-11-18 14:24
Do you have another disk named Macintosh HD? List your **Volumes** directory in terminal and share what you get.

**Comment by bitnautist** [comment] 2020-11-18 14:30
No, only 1 Macintosh HD unless you count Mactinosh HD - Data

obelix@Obelix ~ % diskutil list           
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *2.0 TB     disk0
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk1⁩         2.0 TB     disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +2.0 TB     disk1
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Macintosh HD - Data⁩     671.9 GB   disk1s1
   2:                APFS Volume ⁨Preboot⁩                 553.9 MB   disk1s2
   3:                APFS Volume ⁨Recovery⁩                612.9 MB   disk1s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk1s4
   5:                APFS Volume ⁨Macintosh HD⁩            15.9 GB    disk1s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 15.9 GB    disk1s5s1

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk2
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk2s1
   2:                 Apple_APFS ⁨Container disk5⁩         999.9 GB   disk2s2

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *4.0 TB     disk3
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk3s1
   2:                  Apple_HFS ⁨Movies⁩                  4.0 TB     disk3s2

/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *2.0 TB     disk4
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk4s1
   2:                  Apple_HFS ⁨TV⁩                      2.0 TB     disk4s2

/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +999.9 GB   disk5
                                 Physical Store disk2s2
   1:                APFS Volume ⁨Time Machine Backup⁩     870.8 GB   disk5s1

/dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *20.0 TB    disk6
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk6s1
   2:                 Apple_APFS ⁨Container disk8⁩         20.0 TB    disk6s2

/dev/disk7 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *10.0 TB    disk7
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk7s1
   2:                  Apple_HFS ⁨Asterix⁩                 10.0 TB    disk7s2

/dev/disk8 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +20.0 TB    disk8
                                 Physical Store disk6s2
   1:                APFS Volume ⁨Getafix⁩                 4.8 TB     disk8s1

**Comment by mayankk2308** [comment] 2020-11-18 14:32
That’s not what I meant: `ls /Volumes/`

These appended disk mount points are hidden.

**Comment by bitnautist** [comment] 2020-11-18 14:32
Whoops wrong command...here's the right one...looks like there is another Macintosh HD!

obelix@Obelix ~ % ls /Volumes
Asterix					Movies
Getafix					TV
Macintosh HD				Time Machine Backup
Macintosh HD 1				com.apple.TimeMachine.localsnapshots
obelix@Obelix ~ % ls -l /Volumes
total 0
drwxrwxr-x@ 17 obelix  staff  646 20 Sep 21:51 Asterix
drwxrwxr-x   9 obelix  staff  288 26 Sep 08:38 Getafix
lrwxr-xr-x   1 root    wheel    1 18 Nov 06:26 Macintosh HD -> /
drwxr-xr-x   3 root    wheel   96 17 Nov 14:20 Macintosh HD 1
drwxrwxr-x@ 16 obelix  staff  612  5 Nov 10:43 Movies
drwxrwxr-x@ 14 obelix  staff  544 26 Jul 22:50 TV
drwxrwxr-x@  9 root    wheel  288 18 Nov 06:31 Time Machine Backup
drwxr-xr-x   3 root    wheel   96 17 Nov 13:45 com.apple.TimeMachine.localsnapshots

**Comment by bitnautist** [comment] 2020-11-18 14:45
Can the script extract the correct Volume name from bless --info?

obelix@Obelix ~ % diskutil mount disk1s5
Volume Macintosh HD on disk1s5 mounted

obelix@Obelix ~ % bless --info          
       21910 => Blessed System File is /System/Volumes/Preboot/9084025E-DDD6-4435-89CE-7C73F5ED0212/System/Library/CoreServices/boot.efi
       19519 => Blessed System Folder is /System/Volumes/Preboot/9084025E-DDD6-4435-89CE-7C73F5ED0212/System/Library/CoreServices
The blessed volume in this APFS container is "/Volumes/Macintosh HD 2".
The blessed APFS snapshot for this volume is "9A92851D-96EB-48AD-9E0A-842F8A46DFD8".

**Comment by need-better-name** [comment] 2020-11-18 15:19
@mayankk2308 I just double checked and `bless --getBoot` returns `/dev/disk3s5` now. Either I mistyped it before or it changed between reboots.

I still get the error though.

**Comment by mayankk2308** [comment] 2020-11-18 16:22
@need-better-name @bitnautist I have a new commit - can you please try the latest commit via: https://github.com/mayankk2308/purge-wrangler/wiki/Advanced-Handbook#getting-pre-release-builds

**Comment by need-better-name** [comment] 2020-11-18 16:31
Success!!

**Comment by mayankk2308** [comment] 2020-11-18 16:32
@need-better-name excellent. Once @bitnautist confirms its working, I'll release an update to the script - **v6.3.3**. Cheers.

**Comment by bitnautist** [comment] 2020-11-18 17:29
Success here too! Thanks @mayankk2308! I have donated to the cause. :)

What did Apple change?

**Comment by mayankk2308** [comment] 2020-11-18 17:32
@bitnautist great news. Will release the update soon. Apple changed a lot from Catalina -> Big Sur. This particular issue seems like a minor thing where code assumed appended suffix for mounted volume would be **1**. Fixed that to actually retrieve the mount point correctly and that fixed the issue.

**Comment by bitnautist** [comment] 2020-11-18 17:34
Well that just makes the code better now, no? ;)

**Comment by mayankk2308** [comment] 2020-11-18 17:42
The update is now available. Simply run your existing script as `purge-wrangler` and agree to update. Closing.

**Closed by mayankk2308** 2020-11-18 17:42 UTC

**Comment by Lesliesibbs** [comment] 2020-12-03 12:48
Hi, i'm trying to mount the drive as well and i'm getting 

Could not find disk: /Volumes/High Sierra 10.13.5
Could not find disk: 

Your system volume is read-only. PurgeWrangler cannot proceed.
Please restart your Mac and try again.

i'm running the advanced handbook code which is 

curl -qLs https://bit.ly/2U1zdF5 > purge-wrangler.sh; sed -i "" -e "s/\${script_ver}/master/g" purge-wrangler.sh; sh purge-wrangler.sh; rm purge-wrangler.sh

i've alread rest NVRAM, csrutil disabled, csrutil authenticated-root disabled.

any help?
