### ISSUE TITLE
When patching Nvidia eGPU's, receive error with sed

### ISSUE THREAD

**Issue by gcko** [mayankk2308/purge-wrangler#14] opened 2018-09-21 09:33 UTC
### Problem
When running the script with superuser permissions, I receive an error with sed during selection 2, "Patching Components". The script is running directly from a cloned version of the repository.

### Steps to Reproduce
1. Run `./purge-wrangler`
2. type '2', enter
3. See error

### Expected Behavior
sed should not throw an error

### Screenshots
<img width="457" alt="screen shot 2018-09-21 at 17 28 44" src="https://user-images.githubusercontent.com/521927/45873179-5f01e700-bdc4-11e8-8b05-15916bdbc173.png">

### System Configuration
 - OS: OSX 10.13.6
 - Sonnet Breakaway box 650
 - MSI AERO 1080TI (Nvidia)

**Comment by mayankk2308** [comment] 2018-09-21 16:58
Unable to reproduce, but will address this in a minor update.

**Comment by mayankk2308** [comment] 2018-09-21 22:28
This should be addressed in **4.2.5**.

**Closed by mayankk2308** 2018-09-21 22:28 UTC
