### ISSUE TITLE
Does not work when updating Big Sur from 11.0.1 release to 11.1 beta

### ISSUE THREAD

**Issue by bitnautist** [mayankk2308/purge-wrangler#118] opened 2020-11-17 22:43 UTC
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: 2013 Mac Pro 6,1
- **macOS Version**: 11.1 beta
- **System GPUs**: Dual AMD D500
- **eGPU**: Razer Core X + Radeon VII
- **Script Version**: v6.3.2
- **Script Logs**: [pwlog-2020-11-17-14-20-06.zip](https://github.com/mayankk2308/purge-wrangler/files/5556634/pwlog-2020-11-17-14-20-06.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Purge-wrangler was running in 11.0.1. Updated to 11.1 beta and purge-wrangler was unable to patch files for TB1/2 AMD eGPUs

### Expected Behavior
I expected it to patch files for TB1/2 AMD eGPUs. Once I got the message that the System is read-only, I followed the FAQ: "System is read-only/efi-boot-device error and PurgeWrangler unable to proceed on macOS 11.

Go to System Preferences > Startup Disk and select your macOS 11 boot volume. Then restart. The script should then be able to retrieve the boot volume correctly."

This did not work...purge-wrangler still reports System is read-only.

### Screenshots
Here is the Terminal session when running purge-wrangler...

"obelix@Obelix ~ % purge-wrangler -a
Password:
>> Setup eGPU

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	Radeon VII
GPU Arch	Vega 20 
Thunderbolt	2

Backing up...

Last Backup     11.0.1 [20B29]
Current System  11.1 [20C5048k]

Updating backup...
Update complete.

Patching for AMD eGPUs...
hexdump: /Volumes/Macintosh HD 1/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGPUWrangler.kext/Contents/MacOS/AppleGPUWrangler: No such file or directory
hexdump: /Volumes/Macintosh HD 1/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGPUWrangler.kext/Contents/MacOS/AppleGPUWrangler: Bad file descriptor
Unable to patch for TB1/2 AMD eGPUs.
Generating system log...
rsync: link_stat "/Volumes/Macintosh HD 1/Library/Application Support/Purge-Wrangler/Kexts/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Log generated on the Desktop.

Open an issue on Github and share this file."

**Comment by mayankk2308** [comment] 2020-11-18 00:13
Thanks for the report. Apple might have changed things significantly for those errors to pop up. I will investigate when possible.

**Comment by bitnautist** [comment] 2020-11-18 00:17
Ugh...I hope it's something easy...otherwise my Mac Pro 6,1 work setup is finished. :(

Hope they come up with an M-silicon based Mac Pro soon. :)

**Comment by bitnautist** [comment] 2020-11-18 03:53
Another data point is that Manual Recovery does not work either because of the System being read-only at this point. So now I can't remove Purge-Wrangler and I'm stuck in this one monitor situation. Hooking up another monitor to any of my TB ports does not work...only one monitor. Ugh :(

**Comment by mayankk2308** [comment] 2020-11-18 03:55
After updating macOS, patches are typically automatically reset, so recovery is not required. If you are trying to rollback - that's a different case.

**Comment by mayankk2308** [comment] 2020-11-18 12:52
Patching works normally on **11.1.** I tried patching normally and it worked fine. Perhaps there might have been an issue with reading off the correct disk in your case. Can you retry patching normally (without clicking "yes" on the script notification)?

**Comment by bitnautist** [comment] 2020-11-18 13:29
My system is currently running 11.1 and in a state that running purge-wrangler just results in this:

"obelix@Obelix ~ % purge-wrangler -a
Password:

Your system volume is read-only. PurgeWrangler cannot proceed.
Please restart your Mac and try again."

And this is after selecting correct drive in System Preferences->Startup Disk and restarting...

**Comment by mayankk2308** [comment] 2020-11-18 13:30
Then it’s a duplicate of #117. Please wait for updates there.

**Closed by mayankk2308** 2020-11-18 13:30 UTC
