### ISSUE TITLE
System does not boot after disabling authenticated-root

### ISSUE THREAD

**Issue by mac314** [mayankk2308/purge-wrangler#145] opened 2021-09-17 07:10 UTC
Hello, I tried to update the purge wrangler and have had problems. The last thing I did was disable the authenticated root and now the boot bar gets halfway and stops. When I tried to reinstall Big Sur in recovery mode, it says the volume cannot be downgraded. I really need help! I don’t have the time machine backup for this one and I just need it to return to normal at this point. Thank you in advance!

**Comment by mayankk2308** [comment] 2021-09-17 07:32
> Hello, I tried to update the purge wrangler and have had problems.

what do you mean by “update”?

> The last thing I did was disable the authenticated root and now the boot bar gets halfway and stops.

That alone would not cause an issue. Tell me step by step what you’ve done. Also if you have run this script before (since you say “update” above), then this stuff should already be disabled. Are you absolutely sure SIP is disabled (not just authenticated root)?

> I don’t have the time machine backup for this one and I just need it to return to normal at this point.

Nothing I can do about it. The guide clearly recommends you to take a backup. Just give me a step by step of every single action you’ve taken before this and I’ll see if I can figure it out.

**Comment by mac314** [comment] 2021-09-17 07:44
It told me that purge wrangler was replaced by kryptonite. So it asked me to update. I did so then it said I needed to disable the security... I think the SIP is what you are talking about, so I did so. Then it had to reboot, when I tried again, it said I needed to “authenticate -root disable” so I had to go into recovery mode to do that. Each time it said a restart needed to happen for the changes to take effect. So I restarted. After that it loaded about halfway on the boot up and then came to a stop. I tried to reinstall macOS but it said I could not downgrade and I am on Big Sur
________________________________

**Comment by mac314** [comment] 2021-09-17 07:45
I have run the script before with no issues, but apparently it was not working with Big Sur so it said I needed to update it.
________________________________

**Comment by mayankk2308** [comment] 2021-09-17 07:52
Try NVRAM reset. Also what Mac are you using?

**Comment by mac314** [comment] 2021-09-17 08:00
I am using a MacPro late 2013
________________________________

**Comment by mac314** [comment] 2021-09-17 08:05
I tried the NVRAM reset and it didn't work.
________________________________

**Comment by mac314** [comment] 2021-09-17 08:08
Is there any way to reset it through the terminal and remove the purge wrangler? Or is there a way to get around the reinstall issue? It says it can't downgrade but I have Big Sur on there and so there must be a version gap.
________________________________

**Comment by mayankk2308** [comment] 2021-09-17 08:09
As noted above, please double-check that sip and authenticated root have been enabled, and if not, do so. I would also recommend responding directly on the issues page for quicker updates and because previous posts can be edited so you may miss something: https://github.com/mayankk2308/purge-wrangler/issues/145

**Comment by mayankk2308** [comment] 2021-09-17 08:11
You never really installed purge-wrangler if you couldn’t boot after disabling authenticated root.

**Comment by mayankk2308** [comment] 2021-09-17 08:22
Once you’re back, can you also tell me exactly what version of Big Sur you were running? 11.6 is the latest.

**Comment by mac314** [comment] 2021-09-17 08:37
I am not exactly sure what the last version I had was. I updated to Big Sur several months ago. I have not run Purge Wrangler on Big Sur, but I did have it in a previous OS

**Comment by mayankk2308** [comment] 2021-09-17 08:45
Based on your comments so far, I haven’t been able to narrow down either issue (boot or installation). You can try Shift + Cmd + R recovery to try and fetch latest Big Sur recovery disk and try installing from there. Also did you have FileVault enabled?

**Comment by mac314** [comment] 2021-09-17 08:45
I double checked SIP and authentication root are enabled. I did it again in the terminal and restarted the computer. Fire vault was not on from what I recall

**Comment by mayankk2308** [comment] 2021-09-17 08:47
Gotcha, please try above suggestion for recovery and let me know. If that doesn’t work, I have one final idea.

**Comment by mac314** [comment] 2021-09-17 09:00
I actually tried that three times now. The most recent it had a circle with a line going through it which per the apple site says the computer has an opera rating system in it, just not a version I can use. I don’t know if that means it is just trying to load the older Big Sur instead of the new one, or what.

**Comment by mac314** [comment] 2021-09-17 09:01
It went through the complete download bar before it gave me that circle with the line through it. I forgot to mention that.

**Comment by mayankk2308** [comment] 2021-09-17 09:03
Ok, so couple suggestions going from here then:
1. To get your data, try Safe Mode: https://support.apple.com/guide/mac-help/start-up-your-mac-in-safe-mode-mh21245/mac
2. Add another volume via Disk Utility and install macOS on that, which you can then use to access your data, download full Big Sur installer, and try fixing original install: https://support.apple.com/en-us/HT208891 (the volumes will share your free space, unlike partitions, so you don't need to worry about allocating space permanently to the new partition).

**Comment by mac314** [comment] 2021-09-17 09:25
Safe mode didn’t work. As far as your second option, is that kind of similar to a boot drive? So I create the volume, and download the Big Sur Installer, but once I get back into recovery mode to install, do I need to hold option-A so that it asks where to install? How can I get the option to tell it use the install from the volume and make sure it installs it on the MacintoshHD drive that the computer uses?

**Comment by mayankk2308** [comment] 2021-09-17 09:30
Yes, similar (just that volumes will share all space so not like a traditional partition). Go to Recovery > Disk Utility and Add APFS Volume when your current disk is selected. Then exit that and click Reinstall macOS after which you should be able to choose where to install it. The new volume should allow install. You are not installing "from" the volume, you will install "to" the new volume. I already linked you the support article, not sure what else you need.

**Comment by mayankk2308** [comment] 2021-09-17 09:55
I'll be closing this issue as it is not related to the script itself (it's not a bug), but instead your system environment (there are many MacPro 2013 users who have successfully used this script on macOS Big Sur - including a YT content creator). However, feel free to reach out here if you need further help. You can still respond after issue is marked Closed.

**Closed by mayankk2308** 2021-09-17 09:55 UTC
Labels: question, environment
