### ISSUE TITLE
Catalina breaks DisplayPort video output on NVIDIA Kepler eGPUs

### ISSUE THREAD

**Issue by agg23** [mayankk2308/purge-wrangler#48] opened 2020-02-21 04:04 UTC
### System Configuration
- **Mac**: iMac late-2012 27"
- **macOS Version**: 10.15.3
- **System GPUs**: NVIDIA 680MX
- **eGPU**: AKiTiO Thunder2 + NVIDIA Quadro K2000
- **Script Version**: 6.2.3
- **Script Logs**: [pwlog-2020-02-20-19-22-26.zip](https://github.com/mayankk2308/purge-wrangler/files/4234190/pwlog-2020-02-20-19-22-26.zip)

### Issue Description
No matter what I try, Catalina will not initialize the eGPU as a usable display. The screen never responds at all, and appears to not receive any signal (it doesn't even turn on automatically). I have run through all of the [standard black screen troubleshooting steps](https://github.com/learex/macOS-eGPU#problems) with very little change in results. On boot with eGPU scenarios, the eGPU appears in the Thunderbolt and Graphics sections of System Information (the latter without a recognized display), and the Display section of About this Mac only shows the internal display. On hotplug scenarios, all of the aforementioned views never load, and just sit spinning for extended periods. As expected, the kernel panics when hot unplugged.

I have tested this exact setup across High Sierra, Mojave, and Catalina, all fresh installs, using `purge-wrangler` each time. Both High Sierra and Mojave work on first reboot after install of `purge-wrangler`, with working login screen, sleep, and general graphics acceleration. From what I can tell, nothing significant has changed in Catalina that would cause issues like this, but my research may be lacking.

I realize this is a generally problematic configuration (NVIDIA dGPU without iGPU, TB1, Kepler eGPU) so I wouldn't be terribly surprised if this is just par for the course, but I thought I would ask if you have any ideas since it works fine in previous releases.

**Comment by mayankk2308** [comment] 2020-02-21 12:21
The logs indicate that the GPU is initialized correctly and otherwise functional. I have an NVIDIA GTX 770 and 780 which I can test with and see if I can get a display connected to them functional. Sometimes things change and we can't keep track of it. The number of Kepler eGPU users on macOS Catalina is probably minimal. I shall update my findings here once I finish testing.

**Comment by agg23** [comment] 2020-02-21 13:44
It's unfortunate that it isn't possible to use AMD eGPUs with iMacs with NVIDIA dGPUs for external displays. That was my original plan, and the GPU was recognized fine, but (expectedly) it didn't draw anything either.

**Comment by agg23** [comment] 2020-02-27 03:27
To be thorough, I tested on 10.15.0 to the same effect. Is it common to have System Information spin forever on hotplug scenarios? I haven't found mention of that before, but that may just speak to the efficacy of your tooling

**Comment by mayankk2308** [comment] 2020-02-27 03:29
@agg23 Have been a little too busy to test this. I will have an update for you by the weekend.

I recall the setup has previously worked on 10.15.1 for me (GTX 780) so it may be an issue specific to Catalina + your GPU.

**Comment by mayankk2308** [comment] 2020-03-01 20:08
@agg23 I was also unable to get display output from the GTX 780. Haven't dug deep yet. I do remember getting display output on earlier macOS Catalina builds though. Will try to examine when possible. Leaving this issue open.

**Comment by mayankk2308** [comment] 2020-03-01 20:27
Likely cause that needs further investigation:
<img width="1792" alt="Screen Shot 2020-03-01 at 12 26 01 PM" src="https://user-images.githubusercontent.com/11367902/75633215-ec4f8a80-5bb7-11ea-80e9-3dc1d1f60468.png">

**Comment by agg23** [comment] 2020-03-01 23:04
Interesting. I'm somewhat glad this isn't just a one off. I'll see what I can manage to find out with my meager capabilities.

**Comment by queridiculo** [comment] 2020-03-10 21:52
Similar symptoms here, albeit with slightly different hardware.

* **Mac:**  MacBook Pro (Retina, 15-inch, Mid 2015)
* **macOs version:** 10.15.3
* **System GPUs:** Intel Iris Pro 1536 MB
* **eGPU: ** Razer Core X, PALIT JETSTREAM NVIDIA GeForce GTX 680
* **Script Version: ** 6.2.3
* **Script Logs: ** [pwlog-2020-03-10-22-41-42.zip](https://github.com/mayankk2308/purge-wrangler/files/4314932/pwlog-2020-03-10-22-41-42.zip)

Updated from Mojave today and have been unable to get any output on my external screen since.

eGPU -> USB-C to TB2 -> Macbook Pro
eGPU -> Display Port -> Eizo flexscan ev2785

This setup has not let me down from High Sierra through Mojave.

**Comment by mayankk2308** [comment] 2020-03-10 22:43
@queridiculo thank you for the report. Once I have time, I’ll try a few patches I have in mind to combat this issue.

**Comment by mayankk2308** [comment] 2020-04-03 12:31
Tried a patch or two but no luck so far. Low on time in coming week so will investigate further after that.

**Comment by mayankk2308** [comment] 2020-04-22 04:22
@queridiculo @agg23 It may seem that the issue might be isolated only to Displayport. Could you try HDMI/DVI instead?

**Comment by annaclets** [comment] 2020-04-22 13:19
I am the author of issue #64 "Multiple monitors in High Sierra but only one monitor in Catalina" and I am pleased to report that my problem has been solved by mayankk2308 from two posts back. My eGPU was connected to DisplayPort and HDMI and while there were no problems with thiis in High Sierra, only the HDMI worked in Catalina. When I switched from DP to DVI, problem fixed!

Thanks a lot! It would still be better, though, if DP on Catalina can be fixed.

**Comment by hilga007** [comment] 2020-04-24 21:25
I have a similar bug; different configuration and GPU. 

Main difference with mine: 

- DisplayPort does not work
- HDMI outputs a black screen, with cursor able to be moved and seen on the black screen. 
- No DVI-capable display devices to test that output. 

Should I make my own post, or piggyback off this? 

**System Configuration**

**Mac:** MacBook Pro (15-inch, 2016)
**macOS Version:** 10.15.4
**System GPUs:** Radeon Pro 460 4 GB
                         Intel HD Graphics 530 1536 MB
**eGPU:** Razer Core X + Nvidia GeForce GTX Titan Black 6GB (Kepler)

**Comment by mayankk2308** [comment] 2020-04-24 21:29
@hilga007 no need to create new issue.

**Comment by hilga007** [comment] 2020-04-24 21:36
@mayankk2308 Sounds good. Is there any specific information / logs, etc that you might need from my device? 

I also have a 2012 Mac mini Server with 10.5.4 and TB3-->2/1 adapter I can test with if you need additional sample machines. 

I also have a 2011 iMac with HD 6750 and High Sierra if you need me to compare anything to that machine and version of OS X.

**Comment by mayankk2308** [comment] 2020-04-24 21:38
I'm good - I can reproduce the issue with my systems as well. Just haven't had the time to deep-dive into this issue.

**Comment by hilga007** [comment] 2020-04-24 21:40
Understood. Wish I had the skills to help. Let me know if you need anything.

**Comment by hilga007** [comment] 2020-04-24 22:29
Brief Update: Tested with roommate’s Dell display and Cinema HD display (both DVI) 

In both cases the monitor is recognized in System Preferences with correct resolution and refresh rate; but fails to produce an image. The displays will “light up black” but no actual signal is there.

**Comment by highvoltage12v** [comment] 2020-04-25 23:10
We are having the same issue with 2011 iMacs that have been swapped with MXM Kepler cards on 10.15.4, if we boot without boot screen (not holding ALT on startup) we don't have an internal/External display at all. If we boot holding ALT, we will have login screen, but our external Display output still won't work. I have been looking to this swapping kexts such as "AppleGraphicsPowerManagement.kext" and "AppleGraphicsControl.kext" and some private frameworks, but nothing has helped. A frustrating issue indeed... 
PS: our displays works via eDP.

**Comment by mayankk2308** [comment] 2020-04-26 01:33
@highvoltage12v That sounds like Apple has removed some framebuffer information for Kepler cards. I tried a few more patches/fixes but no luck. Since you are dealing with an internal GPU, you might want to try Hackintosh solution (Lilu + WhateverGreen). At least on my system, it prevented boot so not a viable solution.

One of my suspect kexts is **AppleGraphicsDevicePolicy** (inside AppleGraphicsControl) so once I have time again, I'll look into it. In the meantime, someone else might want to try swapping this kext with one from an older version and see what happens.

**Comment by highvoltage12v** [comment] 2020-04-26 18:43
> @highvoltage12v That sounds like Apple has removed some framebuffer information for Kepler cards. I tried a few more patches/fixes but no luck. Since you are dealing with an internal GPU, you might want to try Hackintosh solution (Lilu + WhateverGreen). At least on my system, it prevented boot so not a viable solution.
> 
> One of my suspect kexts is **AppleGraphicsDevicePolicy** (inside AppleGraphicsControl) so once I have time again, I'll look into it. In the meantime, someone else might want to try swapping this kext with one from an older version of macOS and see what happens.

I actually discovered a solution last night to this. Adding all our Board-ID's to AppleGraphicsDevicePolicy.kext will allow our iMac's to boot to login screen again as well as External DisplayPort Output. I was already running Open Core+WEG/Lilu but that solution didn't fix external DisplayPort output. Adding the board ID's back fixed all 5 models of 2009/2010 iMacs. Maybe this fix could work for eGPU's? I have a GTX 780/Akito Node box I can try after updating an a1502 to 10.15.4
[AppleGraphicsControl.kext.zip](https://github.com/mayankk2308/purge-wrangler/files/4536242/AppleGraphicsControl.kext.zip)
![Screen Shot 2020-04-26 at 1 14 25 PM](https://user-images.githubusercontent.com/64285603/80316498-4477c700-87cc-11ea-8953-ecd63fb2fd3e.png)

**Comment by mayankk2308** [comment] 2020-04-26 19:07
@highvoltage12v please remove the kext immediately. Distributing Apple components individually is not a good idea and as repo owner I may be held liable.

Great job on finding a solution to the issue! We could probably disable board ID checks and see what happens for eGPUs too.

**Comment by highvoltage12v** [comment] 2020-04-27 20:35
> @highvoltage12v please remove the kext immediately. Distributing Apple components individually is not a good idea and as repo owner I may be held liable. **Edit**: I removed it.
> 
> Great job on finding a solution to the issue! We could probably disable board ID checks and see what happens for eGPUs too. Lilu + WhateverGreen does have some options to patch this already (see it's boot-args).

Sorry for that, I'm new to Github.
This issue still persists on ePGU's with Nvidia Kepler, GTX 780Ti working HDMI output, but Displayport output is still not functional. So far I have WEG+Lilu and igfxonln=1 added to com.apple.boot.plist. No status change, I'm pretty sure this kernel flag is for IGPU Framebuffer so it won't have an affect on Nvidia GPU's. The board ID for my test 2012 MBP Mac-4B7AC7E43945597E is already present in AppleGraphicsDevicePolicy, so that has no change on eGPU's either. I swapped IONDRV+NVDResman+Gk100Hal+IOGrapahics from from 10.15.2, still no change on Displayport output. I'd really like to find out what exactly Apple changed.

**Comment by mayankk2308** [comment] 2020-04-27 20:38
@highvoltage12v See WhateverGreen's `agdpmod` flags and try those.

**Comment by annaclets** [comment] 2020-05-03 08:20
If I could share my two cents worth, I use the same eGPU on my Hackintosh and there’s absolutely no problem with DP. Could this problem therefore be not kext-related but rather firmware-related? My affected Apple computers use the same port for DP and thunderbolt, and the firmware could be turning off DP if thunderbolt connection is detected. Perhaps the title of this issue needs to be changed again to “Catalina breaks DisplayPort video output on NVIDIA Kepler eGPUs connected to legacy Apple computers”.

**Comment by mayankk2308** [comment] 2020-05-03 08:45
@annaclets the problem also occurs on my 2018 MacBook Pro so it’s not limited to legacy Mac systems. By virtue of running Hackintosh, whatever patches are involved may have inadvertently addressed this problem for you. A good example is @highvoltage12v ’s case where adding board IDs fixed their problem for a real Mac (Hackintoshes by nature likely have to work around such checks anyway). Highly doubt firmware involvement here because of the nature of the issue (why not block NVIDIA eGPU completely instead). Nonetheless, everything’s conjecture at best. Whenever possible, I’ll try some ideas I have.

**Comment by mayankk2308** [comment] 2020-06-26 09:12
Closing as I won't be investigating this further at this time due to **macOS 11**.

**Closed by mayankk2308** 2020-06-26 09:12 UTC
Labels: environment

**Comment by joevt** [comment] 2021-08-25 05:56
I am running Catalina, MacPro3,1, EVGA GTX 680 Mac Edition (not eGPU). DisplayPort output works in Mojave but not in Catalina until I tried @highvoltage12v 's method of adding my board `Mac-F42C88C8` id to `/System/Library/Extensions//AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist`

```
				<key>Mac-F42C88C8</key>
				<string>none</string>
```

Seems like a strange fix since the `Default` key already points to `none`.

**Comment by joevt** [comment] 2022-01-05 05:32
@mattmcquiff, those board ids are for MacPro6,1, iMacPro1,1, MacPro7,1. Those are from the IOPropertyMatch of com.apple.driver.AppleIntelMCEReporter

You are using OCLP, so your board id is one of those instead of the real board-id of a MacPro5,1.

The fix in this thread is for Catalina without OCLP. I don't know if it works for Big Sur or Monterey or even if it's needed for them.

To edit the file, I used BBEdit.app after mounting the Catalina root volume as writable. It automatically asks for user name and password to edit system files. However, Big Sur and Monterey use snapshots so system files can't be edited as easily. There are ways, but I don't know off the top of my head how.

**Comment by joevt** [comment] 2022-01-17 11:56
@ernestolascano , I would try examining how OCLP does post install patches for adding Kepler GPU support to Montery. Maybe the same method can be used to modify the file. I haven't tried DisplayPort in Monterey yet.

**Comment by mattmcquiff** [comment] 2022-01-20 22:00
So I found a way to write to the file.

It’s detailed here

https://twitter.com/enhancedscurry/status/1275454103900971012 

add the board-Id did nothing. 

I did go to Monterey but found the screen went down to 30hz from the 60hz and overall it lagged.

**Comment by joevt** [comment] 2022-01-22 04:01
I think an update to Catalina 10.15.7 19H1615 removed the patch. I had to reapply it.

Make the system volume writable.
`mount | grep ' on / ' | grep -q 'read-only' && sudo mount -uw /`

Make the changes to a copy of the file.
`sudo cp /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist ~/Documents/Info.plist`
`bbedit ~/Documents/Info.plist`

Copy that back to the original.
`sudo cp ~/Documents/Info.plist /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist`

Rebuild the kernel cache.
`kextcache -I /`

Restart.

Monterey seems to support DisplayPort from my GTX 680 without this patch.
I'll check Big Sur.
