### ISSUE TITLE
Multiple monitors in High Sierra but only one monitor in Catalina

### ISSUE THREAD

**Issue by annaclets** [mayankk2308/purge-wrangler#64] opened 2020-04-22 03:26 UTC
Computers used: Mac mini 2012 (Quad Core i7) & MacBook Pro 2014 (13-in retina)

eGPU used: Nvidia GTX 760 on Akitio Node

Connection used: Apple TB2 cable + Apple TB3 to TB2 adapter

I used purge-wrangler in High Sierra and got multiple monitors, but got only one monitor in Catalina.
Is this a Catalina-specific problem, or do I need to make additional steps/remedies? Pls. advise.

**Comment by mayankk2308** [comment] 2020-04-22 05:29
Duplicate of #48. Closing. Please track progress on fix there.

**Closed by mayankk2308** 2020-04-22 05:29 UTC
